##
#

title: Glasgow Student Housing Co-operative
description: >- 
  Organising for and providing democratic housing to students in Glasgow. Member of Student Co-operative Homes. #NoMoreLandlords
tagline:
  Organising for democratic student housing in Glasgow.
baseurl: "" 
url: "https://glasgowstudenthousingcoop.org"
github_username: gshcoop

# Build settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Theme specifics
show_downloads: false
list_posts: true
#google_analytics: #[tracking id]

paginate: false
date_format: '%d-%m-%Y'
future: false

github:
  is_project_page: false
  is_user_page: true

show_navigation: true

# SEO and social info
logo: /assets/logo.png
instagram:  "https://www.instagram.com/glasgowstudenthousingcoop/"
twitter:    
  username: GSHCoop
  card: summary
facebook:
  publisher: "https://facebook.com/glasgowstudenthousingcoop"
social:
  links:
    - "https://www.instagram.com/glasgowstudenthousingcoop/"
    - "https://twitter.com/GSHCoop"
    - "https://facebook.com/glasgowstudenthousingcoop"
locale: en_GB

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
